# Generated by Django 4.2.3 on 2023-08-05 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Кандитаты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=20, unique=True)),
                ('name_user', models.CharField(max_length=30)),
                ('second_name_user', models.CharField(max_length=30)),
                ('phone_company', models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('image_company', models.ImageField(null=True, upload_to='')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_education', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_specialization', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Специализация',
            },
        ),
        migrations.CreateModel(
            name='TypeEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_of_employment', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Тип занятости',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vacancy', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300, verbose_name='Описание вакансии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.company')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_site.specialization')),
                ('type_of_employment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_site.typeemployment')),
            ],
            options={
                'verbose_name_plural': 'Вакасии',
                'ordering': ['-publication_time'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('image', models.ImageField(null=True, upload_to='')),
                ('profession', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.applicant', verbose_name='Кандидат')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_site.education', verbose_name='Образование')),
                ('key_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.specialization', verbose_name='Ключевые навыки')),
            ],
            options={
                'verbose_name_plural': 'Резюме',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.applicant')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Отправка резюме',
            },
        ),
    ]
