# Generated by Django 4.2.3 on 2023-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0002_alter_customuser_options_applicant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='second_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
