# Generated by Django 4.2.3 on 2023-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0003_applicant_first_name_applicant_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='second_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='about_applicant',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=15, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='place_of_work',
            field=models.CharField(max_length=30, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.CharField(max_length=30, null=True, verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='key_skills',
            field=models.TextField(verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.TextField(verbose_name='Профессия'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
