# Generated by Django 4.2.3 on 2023-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0004_remove_resume_image_remove_resume_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name_of_resume',
            field=models.CharField(default=12, max_length=50, verbose_name='Название резюме'),
            preserve_default=False,
        ),
    ]
