# Generated by Django 4.2.3 on 2023-08-18 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0005_resume_name_of_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-publication_time', '-created_at'], 'verbose_name_plural': 'Вакасии'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='name_company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='name_vacancy',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='town',
        ),
        migrations.AddField(
            model_name='company',
            name='description_company',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='title_company',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='key_skills',
            field=models.CharField(max_length=100, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_vacancy',
            field=models.CharField(default=1, max_length=50, verbose_name='Название вакансии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Потверждена'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=30, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Место положение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publication_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновление вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=30, null=True, verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='specialization',
            field=models.CharField(max_length=30, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_employment',
            field=models.CharField(max_length=30, null=True, verbose_name='Тип занятости'),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='TypeEmployment',
        ),
    ]
