# Generated by Django 4.2.3 on 2023-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0006_alter_vacancy_options_remove_company_name_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title_company',
            field=models.CharField(max_length=20, verbose_name='Название компании'),
        ),
    ]
