# Generated by Django 4.2.3 on 2023-08-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0007_alter_company_title_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-is_published', '-publication_time', '-created_at'], 'verbose_name_plural': 'Вакасии'},
        ),
    ]
