# Generated by Django 4.2.3 on 2023-08-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0008_alter_vacancy_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
