# Generated by Django 4.2.3 on 2023-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0010_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('reject', 'Reject'), ('access', 'Access'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Статус отклика'),
        ),
    ]
