# Generated by Django 4.2.3 on 2023-09-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0011_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-is_published', '-publication_time', '-created_at'], 'verbose_name_plural': 'Вакансии'},
        ),
    ]
