# Generated by Django 4.2.3 on 2023-09-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0012_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search_site.resume', verbose_name='Резюме кандидата'),
            preserve_default=False,
        ),
    ]
