# Generated by Django 4.2.3 on 2023-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0014_resume_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Отклик спрятан'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Приглашение отправлено'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'vacancy')},
        ),
    ]
