# Generated by Django 4.2.3 on 2023-09-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0015_application_hidden_application_is_invited_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
