# Generated by Django 4.2.3 on 2024-01-22 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0017_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeVacancyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Понравившиеся вакансии пользователей',
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
