# Generated by Django 4.2.3 on 2024-01-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0018_likevacancyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToVerificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15, verbose_name='Role of user')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of create request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Запрос на верификацию пользователя',
                'ordering': ['-date_created'],
            },
        ),
    ]
