# Generated by Django 4.2.3 on 2024-02-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_site', '0019_requesttoverificationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeResumeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Понравившиеся резюме пользователей',
                'unique_together': {('user', 'resume')},
            },
        ),
    ]
