# Generated by Django 4.2.3 on 2024-03-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_site', '0020_likeresumeuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribe', models.DateTimeField(auto_now=True, verbose_name='Время подписки на рассылу уведомления')),
                ('notification_recipient', models.CharField(max_length=20, verbose_name='Место отправления получателю')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], max_length=20, verbose_name='Роль пользователя')),
            ],
            options={
                'verbose_name_plural': 'Подписка на уведомления',
                'ordering': ['-date_subscribe'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('MONDAY', 'Monday (Понедельник)'), ('TUESDAY', 'Tuesday (Вторник)'), ('WEDNESDAY', 'Wednesday (Среда)'), ('THURSDAY', 'Thursday (Четверг)'), ('FRIDAY', 'Friday (Пятница)'), ('SATURDAY', 'Saturday (Суббота)'), ('SUNDAY', 'Sunday (Воскресенье)')], default='Monday', max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Дни уведомления пользователя',
            },
        ),
        migrations.CreateModel(
            name='NotificationsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_send', models.TimeField()),
                ('end_start_send', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Время уведомления пользователя',
            },
        ),
        migrations.CreateModel(
            name='TypeNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('phone', 'Phone')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Типы уведомления пользователей',
            },
        ),
        migrations.CreateModel(
            name='NotificationsEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notifications')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Уведомления компаниям',
                'ordering': ['-vacancy__updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notifications')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_site.resume')),
            ],
            options={
                'verbose_name_plural': 'Уведомления кандидатам',
                'ordering': ['-resume__updated_at'],
            },
        ),
        migrations.AddField(
            model_name='notifications',
            name='days_notifications',
            field=models.ManyToManyField(to='notifications.notificationsdays'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='time_notifications',
            field=models.ForeignKey(default=notifications.models.NotificationsTime.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='notifications.notificationstime'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='type_notifications',
            field=models.ManyToManyField(to='notifications.typenotifications'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
